Datacenter: "europe"

API:
  ListenAddress: "127.0.0.1"
  ListenPort: 1234

Log:
  Level: "info"
  Pretty: true

Authentication:
  LDAP:
    URL: "ldaps://URL.local"
    BindDN: "cn=<user>,OU=<ou>,DC=<local>"
    BaseDN: "DC=<local>"
    Password: "<some_password>"
    WorkersCount: 10
    Timeout: 5s
    MaxConnectionLifetime: 1m
    InsecureSkipVerify: false

NetBox:
  URL: "https://netbox.local"
  APIKey: "<some_key>"
  DatacenterFilterKey: "site_group"
  LimitPerPage: 500

Build:
  Interval: "30m"
  AllDevicesMustBuild: false
