Datacenter: "europe"
LogLevel: "error"

API:
  ListenAddress: "127.0.0.1"
  ListenPort: 1234

Log:
  Level: "info"
  Pretty: true

Authentication:
  LDAP:
    InsecureSkipVerify: "false"
    URL: "ldaps://URL.local"
    BindDN: "cn=<user>,OU=<ou>,DC=<local>"
    BaseDN: "DC=<local>"
    Password: "<some_password>"
    MaxWorkers: 10

NetBox:
  URL: "https://netbox.local"
  APIKey: "<some_key>"
  DatacenterFilterKey: "site_group"

Build:
  Interval: "30m"